# PR Preview Configuration for Cloudflare Workers
# This configuration is used for ephemeral PR deployments
# Worker name is dynamically set via CLI: --name phialo-pr-{number}

main = "src/index.ts"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[assets]
directory = "../phialo-design/dist"
binding = "ASSETS"

[build]
command = "npm run build"
cwd = "../phialo-design"

[vars]
ENVIRONMENT = "preview"

# Analytics Engine binding for Web Vitals
[[analytics_engine_datasets]]
binding = "VITALS_ANALYTICS"
dataset = "VITALS_ANALYTICS"