name: Cleanup Ephemeral Preview

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    environment: cloudflare
    permissions:
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Delete ephemeral worker
        id: delete-worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          WORKER_NAME="phialo-pr-${{ github.event.pull_request.number }}"
          
          # Check if the worker exists
          echo "Checking if worker $WORKER_NAME exists..."
          
          # Use wrangler deployments list to check if worker exists
          # The command will return exit code 0 even if worker doesn't exist
          WORKER_EXISTS=$(npx wrangler deployments list --name "$WORKER_NAME" 2>&1 | grep -q "No deployments found" && echo "false" || echo "true")
          
          if [ "$WORKER_EXISTS" = "true" ]; then
            echo "Worker $WORKER_NAME exists, deleting..."
            npx wrangler delete --name "$WORKER_NAME" --force
            echo "worker_deleted=true" >> $GITHUB_OUTPUT
          else
            echo "Worker $WORKER_NAME does not exist, skipping deletion"
            echo "worker_deleted=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Comment on PR
        if: steps.delete-worker.outputs.worker_deleted == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const pr_number = context.issue.number;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
              body: '## 🧹 Preview Cleaned Up\n\nThe ephemeral preview environment for this PR has been deleted.'
            });