name: Dependabot auto-triage
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  issues: write
  contents: read

jobs:
  auto-triage:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || (github.event.pull_request.user.login == 'dependabot[bot]' && github.event_name == 'pull_request_target')
    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      
      - name: Label security updates
        if: steps.metadata.outputs.ghsa-id != ''
        run: |
          gh pr edit "$PR_URL" --add-label "security"
          gh pr edit "$PR_URL" --add-label "priority:high"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      - name: Label patch updates
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: |
          gh pr edit "$PR_URL" --add-label "semver:patch"
          gh pr edit "$PR_URL" --add-label "priority:low"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      - name: Label minor updates
        if: steps.metadata.outputs.update-type == 'version-update:semver-minor'
        run: |
          gh pr edit "$PR_URL" --add-label "semver:minor"
          gh pr edit "$PR_URL" --add-label "priority:medium"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      - name: Label major updates
        if: steps.metadata.outputs.update-type == 'version-update:semver-major'
        run: |
          gh pr edit "$PR_URL" --add-label "semver:major"
          gh pr edit "$PR_URL" --add-label "priority:high"
          gh pr edit "$PR_URL" --add-label "breaking-change"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      - name: Request review for production dependencies
        if: steps.metadata.outputs.dependency-type == 'direct:production'
        run: |
          gh pr edit "$PR_URL" --add-reviewer "barde"
          gh pr comment "$PR_URL" --body "⚠️ This updates a **production dependency**. Please review carefully before merging."
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      - name: Comment on major version updates
        if: steps.metadata.outputs.update-type == 'version-update:semver-major'
        run: |
          cat << 'EOF' | gh pr comment "$PR_URL" --body-file -
          🚨 **Major version update detected!**
          
          This PR updates ${{ steps.metadata.outputs.dependency-name }} from ${{ steps.metadata.outputs.previous-version }} to ${{ steps.metadata.outputs.new-version }}.
          
          Please check:
          - [ ] Breaking changes in the changelog
          - [ ] Update any affected code
          - [ ] Run comprehensive tests
          - [ ] Update documentation if needed
          EOF
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}